mitigate security risks exposed by overlay-helper
(hopefully)
https://github.com/graysky2/profile-sync-daemon/issues/235

diff --git a/common/psd-overlay-helper b/common/psd-overlay-helper
--- a/common/psd-overlay-helper
+++ b/common/psd-overlay-helper
@@ -27,6 +27,20 @@ OPTIND=1
 ## TODO - pass error codes back to psd so it can break if the mount command fails
 case "$1" in
 	mountup)
+		# dont overlay lowerdirs where the owner of upperdir/workdir does not
+		# have write access to
+		user=$(stat -c %U "$TMP")
+		if ! sudo -u "$user" test -w "$BACKUP"; then
+			echo "User $user has no write permissions for $BACKUP. Aborting..." >&2
+			exit 1
+		fi
+
+		user=$(stat -c %U "$UPPER")
+		if ! sudo -u "$user" test -w "$BACKUP"; then
+			echo "User $user has no write permissions for $BACKUP. Aborting..." >&2
+			exit 1
+		fi
+
 		if [[ $OLFSVER -eq 23 ]]; then
 			mount -o nosuid,nodev -t overlay overlaid -olowerdir="$BACKUP",upperdir="$UPPER",workdir="$WORK" "$TMP"
 		elif [[ $OLFSVER -eq 22 ]]; then
